### ISSUE TITLE
Endpoint for groups

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/oscm-identity#16]
**Summary**
Provide an endpoint for clients, e.g. oscm-core to create groups, assign and deassign members from groups

**Details**
* Group naming convension is required to distinguish OSCM related groups from others.  
Convention (to be agreed):  `displayName := OSCM_<organization name>`
* Group membership must be unique => raise error if user is already assigned to other OSCM group.

**Ressources**
* MS Graph API to create groups
  https://docs.microsoft.com/en-us/graph/api/group-post-groups?view=graph-rest-1.0&tabs=http
* MS Graph API add members
  https://docs.microsoft.com/en-us/graph/api/group-post-members?view=graph-rest-1.0&tabs=http
  Since such functions go beyond the OIDC standard, the implemtion needs to be exchange-able. All MS releated access needs to be encapsuluated behind iternal interfaces.

**Acceptance criteria**
- [ ] Access implementation is exchange-able and usage is generic
- [ ] TBD

**Additional context**
Later

**Comment by kowalczyka** [comment]
Splitted into separate tasks:
- https://github.com/servicecatalog/oscm-identity/issues/26
- https://github.com/servicecatalog/oscm-identity/issues/27
