### ISSUE TITLE
Introduce mechanism of refreshing the token when it is expired

### ISSUE THREAD

**Issue by kowalczyka** [servicecatalog/oscm-identity#19]
**Summary**
Access token after some time become expired. It must be refreshed so that user is still logged in and can use it for accessing secured resources.

**Details**
N/A

**Acceptance criteria**
- [ ] access token in refreshed automatically
- [ ] no errors are present after token expiration time
- [ ] refresh token validation is implemented
- [ ] overall code coverage is at least 80%

**Additional context**
N/A

**Comment by Crystalzord** [comment]
Part on the identity side is done and merged to master. (refresh endpoint added)
