### ISSUE TITLE
Endpoint for retrieving users assigned to a given group

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/oscm-identity#28]
**Summary**
Endpoint for rerieving users assigned to a given group.

**Details**

- MS Graph API list members
https://docs.microsoft.com/en-us/graph/api/group-list-members?view=graph-rest-1.0&tabs=http

**Acceptance criteria**
- [x] endpoint (secured with bearer token) for listing all users assigned to the group 

**Additional context**
N/A

**Comment by kowalczyka** [comment]
Done with https://github.com/servicecatalog/oscm-identity/commit/9e495832ab3afd2618babc030e22eb1216f24742
