### ISSUE TITLE
Check wether nonce validation is necessary/correct

### ISSUE THREAD

**Issue by adamczykba** [servicecatalog/oscm-identity#39]
**Summary**
Recently we've came to a conclusion that nonce in id/access token can be validated in a wrong way.
As documentation is bit ambigious it is required to validate wether nonce is validated properly and/or its validation is needed at all.

**Details**
N/A

**Acceptance criteria**
- [x] nonce validation is revised
- [x] code coverage is unaffected

**Additional context**
- [OpenID Connect @ AzureAD](https://docs.microsoft.com/en-us/azure/active-directory/develop/v1-protocols-openid-connect-code)
- [Implicit grant flow @ AzureAD](https://docs.microsoft.com/en-us/azure/active-directory/develop/v1-oauth2-implicit-grant-flow)
- [ID Token Valiation @ AzureAD](https://docs.microsoft.com/en-us/azure/active-directory/develop/id-tokens)
- [Access Token Validation @ AzureAD](https://docs.microsoft.com/en-us/azure/active-directory/develop/access-tokens)

**Comment by kowalczyka** [comment]
Closing as this was done within https://github.com/servicecatalog/oscm-identity/commit/270c0e44d011de6fb9eab30c427e34fe9b387952
