### ISSUE TITLE
Error message required for assigning group members endpoint

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/oscm-identity#48]
**Summary**
Improve error handling returning error message if user is already assigned to a group. General HTTP error code is not sufficient. 

**Details**
Following message is logged 
"org.oscm.identity.error.InvalidRequestException: User admin@ctmg.onmicrosoft.com is already member of one of the groups"

The message tail after ":" is addressing the caller and needed at the client side. It should be returned with the json response. 

**Acceptance criteria**
- [x] HTTP error 400 and json message details

**Additional context**
N/A

**Comment by GoebelL** [comment]
Or better return a different error code for this case when the group already exists. E.g. HTTP 408 Conflict.

**Comment by adamczykba** [comment]
@GoebelL 
It turned out that the functionality is already working as expected (with code 400), so I'm closing this issue for now.

![obraz](https://user-images.githubusercontent.com/47355402/67391306-b3b2fb00-f59e-11e9-9d73-937dfd44e515.png)
