### ISSUE TITLE
Minor logging improvement

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/oscm-identity#49]
**Summary**
Remove unneeded logging statements.

**Details**
Docker logs full with "Token Validated" entries that contain no information.
![grafik](https://user-images.githubusercontent.com/14805690/65261159-ea14da80-db07-11e9-8b2e-e3ec3bdebddf.png)

**Acceptance criteria**
- [x] No logging of validation success on INFO level

**Comment by adamczykba** [comment]
This issue is no longer valid, as this behaviour was changed in scope of #38.
Taking that into regard - I'm closing this issue.
