### ISSUE TITLE
Default tenant could not be loaded

### ISSUE THREAD

**Issue by kowalczyka** [servicecatalog/oscm-identity#5]
**Version Info**
Latest

**Describe the bug**
Default tenant is not loaded.

**How to Reproduce**
1. Start the application with java -jar oscm-identity.jar'
2. Go to http://localhost:9090/oscm-identity/login

**Observed behavior**
Error message is displayed

**Expected behavior**
User is redirected to configured IdP. 

**Additional context**
Problem does not exist whe application is started with mvn spring-boot:run.
As an improvement tenant configuration should be loaded from file external to application jar itself.

**Comment by GoebelL** [comment]
The tenant properties files have to be exposed to the operator. Instead of compiling them into the application binary, these properties files should be contained in a defined host directory that is mounted into the container. At present the application is not startable.
