### ISSUE TITLE
Additional validation for access token

### ISSUE THREAD

**Issue by kowalczyka** [servicecatalog/oscm-identity#56]
**Summary**
As we are working on adapting OSCM SOAP webservices for using access token authentication, current validation functionality must extended to validate access token retrieved within the client credentials flow.

**Details**
Validation should support audience verification which is included in the token. In client credentials flow it shoud be similar to the scope which was included in access token request. This means that token's audience should be equal to tenant's configuration oidc.appIdUri property. Probably separate token type would be needed for this type of validation.

**Acceptance criteria**
- [x] current validation endpoint must support audience verification for access token (retrieved within client credentials flow)

**Additional context**
N/A

**Comment by adamczykba** [comment]
Closed as not applicable anymore, as discussed with @kowalczyka
