### ISSUE TITLE
Increase code coverage

### ISSUE THREAD

**Issue by adamczykba** [servicecatalog/oscm-identity#6]
**Summary**
Right now, code coverage for this module is at the level of about 60, let's increase it to 80%

**Details**
N/A

**Acceptance criteria**
- [ ] code coverage for this repository is at least 80%

**Additional context**
N/A

**Comment by adamczykba** [comment]
Reopened due to #22

**Comment by kowalczyka** [comment]
Closing as this will be resolved within next tasks implemantations
